export interface TwilioStatusCallback {
  readonly Called: string;
  readonly RecordingUrl: string;
  readonly ToState: string;
  readonly CallerCountry: string;
  readonly Direction: string;
  readonly Timestamp: string;
  readonly CallbackSource: string;
  readonly SipResponseCode: string;
  readonly CallerState: string;
  readonly ToZip: string;
  readonly SequenceNumber: string;
  readonly CallSid: string;
  readonly To: string;
  readonly CallerZip: string;
  readonly ToCountry: string;
  readonly CalledZip: string;
  readonly ApiVersion: string;
  readonly RecordingSid: string;
  readonly CalledCity: string;
  readonly CallStatus: string;
  readonly Duration: string;
  readonly From: string;
  readonly CallDuration: string;
  readonly AccountSid: string;
  readonly CalledCountry: string;
  readonly CallerCity: string;
  readonly ToCity: string;
  readonly FromCountry: string;
  readonly Caller: string;
  readonly FromCity: string;
  readonly CalledState: string;
  readonly FromZip: string;
  readonly RecordingDuration: string;
  readonly FromState: string;
}

// export interface TwilioStatusCallback {
//   readonly Called: "+447595672701";
//   readonly RecordingUrl: "https://api.twilio.com/2010-04-01/Accounts/AC0c40e60514252ba144cc6a34b61c7484/Recordings/RE6cda74cc088486f393ebe69176f46d56";
//   readonly ToState: "";
//   readonly CallerCountry: "GB";
//   readonly Direction: "outbound-api";
//   readonly Timestamp: "Tue, 01 Mar 2022 20:03:54 +0000";
//   readonly CallbackSource: "call-progress-events";
//   readonly SipResponseCode: "200";
//   readonly CallerState: "";
//   readonly ToZip: "";
//   readonly SequenceNumber: "0";
//   readonly CallSid: "CA6aaa873caa8d823b8c9a5004438a793e";
//   readonly To: "+447595672701";
//   readonly CallerZip: "";
//   readonly ToCountry: "GB";
//   readonly CalledZip: "";
//   readonly ApiVersion: "2010-04-01";
//   readonly RecordingSid: "RE6cda74cc088486f393ebe69176f46d56";
//   readonly CalledCity: "";
//   readonly CallStatus: "completed";
//   readonly Duration: "1";
//   readonly From: "+447488880401";
//   readonly CallDuration: "21";
//   readonly AccountSid: "AC0c40e60514252ba144cc6a34b61c7484";
//   readonly CalledCountry: "GB";
//   readonly CallerCity: "";
//   readonly ToCity: "";
//   readonly FromCountry: "GB";
//   readonly Caller: "+447488880401";
//   readonly FromCity: "";
//   readonly CalledState: "";
//   readonly FromZip: "";
//   readonly RecordingDuration: "21";
//   readonly FromState: "";
// }
